### testing the train model of titanic datasets without using the pipelines


In [1]:
import numpy as np
import pickle

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [3]:
# taking a random test data as 
# Pclass/gender/age/sibsp/Parch/Embarked
test_input = np.array([2,'male',31.0,0,0,'S'],dtype=object).reshape(1,6)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex

array([[0., 1.]])

In [7]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

C:\Users\dspri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [8]:
test_input_embarked


array([[0., 0., 1.]])

In [9]:
test_input_age = test_input[:,2].reshape(1,1)

In [10]:
test_input_age

array([[31.0]], dtype=object)

In [11]:
# concatiatinf all modified columns with the remaining columns
test_input_transformed = np.concatenate((test_input[:,[0,3,4]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [12]:
test_input_transformed.shape[1]

9

In [13]:
# predicting the out whether the person will survive or not according to the trained data
clf.predict(test_input_transformed)

array([0])