### Column Transformer

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('../datasets/covid_toy.csv')

In [3]:
data.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [4]:
data.shape[0]

100

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [6]:
data['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
data['age'].value_counts()

age
65    4
34    4
19    4
5     3
69    3
42    3
49    3
20    3
64    3
83    3
27    3
51    3
82    3
16    2
60    2
38    2
23    2
24    2
81    2
10    2
80    2
47    2
71    2
73    2
12    2
11    2
25    2
75    2
14    2
56    1
59    1
6     1
46    1
8     1
54    1
48    1
68    1
17    1
26    1
44    1
66    1
18    1
72    1
22    1
50    1
55    1
74    1
15    1
33    1
13    1
40    1
70    1
84    1
31    1
79    1
Name: count, dtype: int64

In [8]:
data['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [9]:
data['fever'].value_counts()

fever
101.0    17
98.0     17
104.0    14
100.0    13
99.0     10
102.0    10
103.0     9
Name: count, dtype: int64

In [10]:
data['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [11]:
data['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [12]:
### Finding the number of null values in each columns
data.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [16]:
### splitting data into x and y
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.drop(columns=['has_covid']),data['has_covid'],test_size=0.3,random_state=42)

In [17]:
x_train.shape[0]

70

# Aam Zindagi

In [20]:
# Adding simple inputer to the fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

# Applying simple imputer over the test data also
x_test_fever = si.fit_transform(x_test[['fever']])


In [23]:
x_train_fever

array([[ 98.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [100.96721311],
       [ 99.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [100.96721311],
       [ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [100.96721311],
       [ 98.        ],
       [ 99

In [25]:
# Applying Ordinal Encoding to cough column
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# Applying Ordinal Encoding over test data 
x_test_cough = oe.fit_transform(x_test[['cough']])

In [26]:
x_train

,age,gender,fever,cough,city
11,65,Female,98.0,Mild,Mumbai
47,18,Female,104.0,Mild,Bangalore
85,16,Female,103.0,Mild,Bangalore
28,16,Male,104.0,Mild,Kolkata
93,27,Male,100.0,Mild,Kolkata
...,...,...,...,...,...
60,24,Female,102.0,Strong,Bangalore
71,75,Female,104.0,Strong,Delhi
14,51,Male,104.0,Mild,Bangalore
92,82,Female,102.0,Strong,Kolkata


In [27]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [32]:
# Applying one hot encoding over gender and city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# Aplying one hot encoding over test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

In [33]:
# Extracting the age column from the data 
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values 

In [34]:
# Merging all the column into single one
x_train_transform = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
x_test_transform = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

# Mentoss Zindagi

In [38]:
from sklearn.compose import ColumnTransformer


In [40]:
transformer = ColumnTransformer(transformers=[
    ('tf1',SimpleImputer(),['fever']),
    ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [41]:
transformer.fit_transform(x_train)

array([[ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [100.96721311,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [42]:
transformer.fit_transform(x_test)

array([[104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  17.       ],
       [ 98.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  83.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  68.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  72.       ],
       [102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  50.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [100.5862069,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [103.       ,   0.   