# Stochastic Gradient desendent  

In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time


In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X.shape

(442, 10)

In [4]:
y.shape

(442,)

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [6]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [7]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [8]:
x_train.shape

(309, 10)

In [11]:
y_train.shape

(309,)

In [12]:
x_test

array([[ 0.04534098, -0.04464164, -0.00620595, ...,  0.03430886,
         0.03243232, -0.0052198 ],
       [ 0.09256398, -0.04464164,  0.03690653, ..., -0.03949338,
        -0.02251653, -0.02178823],
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00189471, ...,  0.01770335,
        -0.03581619,  0.00306441],
       [ 0.01628068, -0.04464164, -0.04500719, ..., -0.0763945 ,
        -0.04257085,  0.04034337],
       [ 0.01991321,  0.05068012,  0.04552903, ...,  0.02692863,
         0.04560437,  0.04034337]], shape=(133, 10))

In [14]:
lr = LinearRegression()

In [15]:
lr.fit(x_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [16]:
lr.coef_

array([  29.25401303, -261.7064691 ,  546.29972304,  388.39834056,
       -901.95966819,  506.76324136,  121.15435079,  288.03526689,
        659.26895081,   41.37670105])

In [18]:
lr.intercept_

np.float64(151.00821291456543)

In [19]:
y_pred = lr.predict(x_test)

In [20]:
y_pred

array([138.46970031, 181.10052342, 125.34400904, 292.75977277,
       123.8830531 ,  91.89830434, 257.26463123, 177.76169318,
        84.98549706, 109.15960992,  94.4855284 , 166.13235108,
        57.40742502, 206.13897354,  97.7811842 , 131.00472765,
       214.29789972, 252.52907661, 199.66656381, 219.49985634,
       203.23671317,  88.00656925,  70.65108459, 186.92233427,
       155.81266751, 162.81022205, 191.93135706, 184.72924276,
        46.62920829, 108.26566599, 178.14743952,  91.35065005,
       127.72125745, 184.04205666, 172.23799897, 189.51548863,
       121.83265708, 117.75339206, 145.67950306,  58.57563401,
        72.55421321, 107.27571105, 166.15280313, 153.29339984,
       165.19282154,  62.95752038,  73.58909449, 110.05656189,
        54.49723354, 164.88920632, 152.49472803,  63.8874565 ,
       111.4354561 , 108.34936269, 179.96973311, 158.70054112,
        95.04833555, 209.68990406, 118.37356519,  69.69946093,
       189.04680627, 204.99138626, 140.26840176, 105.75

In [21]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184., 144., 150., 280., 125.,  59.,  65., 281., 277., 167.,  90.,
        72., 178.,  88., 270., 101., 197.,  97.,  53.,  71., 262.,  52.,
       102., 166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121.,
       128., 104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93.,
       232.])

In [22]:
r2_score(y_test,y_pred)

0.4772897164322617

# Stochastic_Gradient_desent_class

In [33]:
class SGDRegressor:
    def __init__(self,learning_rate,epochs):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None

        # fit methd
    def fit(self,x_train,y_train):
            # initialize coef
            self.intercept_ = 0
            self.coef_ = np.ones(x_train.shape[1])

            for i in range(self.epochs):
                for j in range(x_train.shape[0]):
                    # random index
                    idx = np.random.randint(0,x_train.shape[0])

                    # finding intercept
                    y_hat = np.dot(x_train[idx],self.coef_) + self.intercept_
                    intercept_der = -2*(y_train[idx] - y_hat)
                    self.intercept_ = self.intercept_ - ( self.learning_rate * intercept_der)
                    
                    # finding slope
                    coef_der = -2*np.dot((y_train[idx] - y_hat),x_train[idx])
                    self.coef_ = self.coef_ - (self.learning_rate*coef_der)

    def predict(self,x_test):
            return np.dot(x_test,self.coef_) + self.intercept_

In [34]:
sgd = SGDRegressor(0.01,50)

In [35]:
sgd.fit(x_train,y_train)

In [36]:
y_pred2 = sgd.predict(x_test)

In [37]:
r2_score(y_pred2,y_test)

-0.5655692140404123

In [38]:
y_pred2

array([154.94447934, 161.41200297, 150.31486087, 262.99754148,
       139.9871623 , 117.62403542, 226.71524433, 193.69612841,
       100.15828157, 127.7911977 , 105.21962521, 136.15887082,
        69.3405494 , 203.47665481, 116.37188051, 131.76216473,
       211.1799818 , 232.76917296, 168.67937825, 202.78603238,
       171.7082298 , 103.67146267,  85.91395531, 182.59374593,
       140.02065834, 163.79342666, 177.53633767, 171.73810547,
        60.48155612, 134.01809517, 170.2226867 , 101.94031178,
       136.98945481, 178.314765  , 171.57342231, 181.29632459,
       134.92943816, 138.89832122, 165.56649528,  73.45905591,
        95.52497134, 122.99300252, 151.14177428, 165.4312852 ,
       162.03958228,  78.64792291,  87.23408812,  99.93671506,
        72.96553952, 138.69698794, 130.97065201,  73.12090068,
       133.02722446, 112.40230825, 179.22780192, 137.8295766 ,
       111.15643483, 183.75073339, 111.02527634,  69.2442194 ,
       179.82044437, 169.82674737, 132.78327302, 125.32

In [39]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184., 144., 150., 280., 125.,  59.,  65., 281., 277., 167.,  90.,
        72., 178.,  88., 270., 101., 197.,  97.,  53.,  71., 262.,  52.,
       102., 166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121.,
       128., 104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93.,
       232.])